from tinydb import TinyDB
from tinydb.storages import MemoryStorage

# an in-memory database of all known ingredients
entries = [
    {"english": "coconut milk"                 , "category": "nometro"     , "ingredient" : "kokosmilch"                       , "allergens" : []},
    {"english": "kala namak salt"              , "category": "nometro"     , "ingredient" : "kala namak (eiersalz)"            , "allergens" : []},
    {"english": "coconut oil"                  , "category": "nometro"     , "ingredient" : "kokosfett"                        , "allergens" : []},
    {"english": "black olives"                 , "category": "nometro"     , "ingredient" : "schwarze oliven"                  , "allergens" : []},
    {"english": "nutritional yeast"            , "category": "nometro"     , "ingredient" : "hefeflocken"                      , "allergens" : []},
    {"english": "light soy sauce (gluten free)", "category": "nometro"     , "ingredient" : "helle sojasauce (glutenfrei)"     , "allergens" : []},
    {"english": "peanut butter"                , "category": "nometro"     , "ingredient" : "erdnussbutter"                    , "allergens" : ["erdnüsse"]},
    {"english": "black sesame seeds"           , "category": "nometro"     , "ingredient" : "schwarzer sesam"                  , "allergens" : ["sesam"]},
    {"english": "sticky rice"                  , "category": "nometro"     , "ingredient" : "klebreis"                         , "allergens" : []},
    {"english": "soy chunks"                   , "category": "nometro"     , "ingredient" : "soja chunks"                      , "allergens" : ["soja"]},
    {"english": "tempeh"                       , "category": "nometro"     , "ingredient" : "tempeh"                           , "allergens" : ["soja" , "histamin"]},
    {"english": "tahini"                       , "category": "nometro"     , "ingredient" : "tahin"                            , "allergens" : ["sesam"]},
    {"english": "miso"                         , "category": "nometro"     , "ingredient" : "miso"                             , "allergens" : ["histamin", "soja"]},
    {"english": "tofu"                         , "category": "nometro"     , "ingredient" : "tofu"                             , "allergens" : ["soja"]},
    {"english": "tempe"                        , "category": "nometro"     , "ingredient" : "tempe"                            , "allergens" : ["soja","histamin"]},
    {"english": "soy bean sprouts"             , "category": "nometro"     , "ingredient" : "sojasprossen"                     , "allergens" : ["soja"]},
    {"english": "wheat gluten powder"          , "category": "nometro"     , "ingredient" : "seitanpulver"                     , "allergens" : ["gluten"]},
    {"english": "gas"                          , "category": "hygiene"     , "ingredient" : "gas"                              , "allergens" : []},
    {"english": "disinfectant"                 , "category": "hygiene"     , "ingredient" : "desi"                             , "allergens" : []},
    {"english": "trash bags"                   , "category": "hygiene"     , "ingredient" : "müllbeutel"                       , "allergens" : []},
    {"english": "sponges"                      , "category": "hygiene"     , "ingredient" : "schwämme"                         , "allergens" : []},
    {"english": "lappen"                       , "category": "hygiene"     , "ingredient" : "lappen"                           , "allergens" : []},
    {"english": "steel wool"                   , "category": "hygiene"     , "ingredient" : "stahlwolle"                       , "allergens" : []},
    {"english": "paper towels"                 , "category": "hygiene"     , "ingredient" : "küchenrolle"                      , "allergens" : []},
    {"english": "dishwashing soap"             , "category": "hygiene"     , "ingredient" : "spüli"                            , "allergens" : []},
    {"english": "hand soap"                    , "category": "hygiene"     , "ingredient" : "handseife"                        , "allergens" : []},
    {"english": "rubber gloves"                , "category": "hygiene"     , "ingredient" : "gummihandschuhe"                  , "allergens" : []},
    {"english": "dishwashing gloves"           , "category": "hygiene"     , "ingredient" : "spülhandschuhe"                   , "allergens" : []},
    {"english": "baking sheets"                , "category": "hygiene"     , "ingredient" : "backpapier"                       , "allergens" : []},
    {"english": "red wine"                     , "category": "getränke"    , "ingredient" : "rotwein"                          , "allergens" : ["alkohol", "histamin"]},
    {"english": "lemon juice"                  , "category": "getränke"    , "ingredient" : "zitronensaft"                     , "allergens" : []},
    {"english": "white wine"                   , "category": "getränke"    , "ingredient" : "weißwein"                         , "allergens" : ["alkohol"]},
    {"english": "vodka"                        , "category": "getränke"    , "ingredient" : "wodka"                            , "allergens" : ["alkohol"]},
    {"english": "tomatos"                      , "category": "gemüse/obst" , "ingredient" : "tomaten"                          , "allergens" : []},
    {"english": "cucumber"                     , "category": "gemüse/obst" , "ingredient" : "gurke"                            , "allergens" : []},
    {"english": "mushrooms"                    , "category": "gemüse/obst" , "ingredient" : "champis"                          , "allergens" : []},
    {"english": "savoy cabbage"                , "category": "gemüse/obst" , "ingredient" : "wirsing"                          , "allergens" : []},
    {"english": "white cabbage"                , "category": "gemüse/obst" , "ingredient" : "weißkohl"                         , "allergens" : []},
    {"english": "carrots"                      , "category": "gemüse/obst" , "ingredient" : "möhren"                           , "allergens" : []},
    {"english": "fresh spinach"                , "category": "gemüse/obst" , "ingredient" : "frischer spinat"                  , "allergens" : []},
    {"english": "fresh mint"                   , "category": "gemüse/obst" , "ingredient" : "frische minze"                    , "allergens" : []},
    {"english": "fresh parsley"                , "category": "gemüse/obst" , "ingredient" : "frische petersilie"               , "allergens" : []},
    {"english": "spring onions"                , "category": "gemüse/obst" , "ingredient" : "frühlingszwiebeln"                , "allergens" : ["zwiebel"]},
    {"english": "fresh dill"                   , "category": "gemüse/obst" , "ingredient" : "frischer dill"                    , "allergens" : []},
    {"english": "fresh chives"                 , "category": "gemüse/obst" , "ingredient" : "frischer schnittlauch"            , "allergens" : ["zwiebel"]},
    {"english": "onions"                       , "category": "gemüse/obst" , "ingredient" : "zwiebeln"                         , "allergens" : ["zwiebel"]},
    {"english": "red onions"                   , "category": "gemüse/obst" , "ingredient" : "rote zwiebeln"                    , "allergens" : ["zwiebel"]},
    {"english": "garlic"                       , "category": "gemüse/obst" , "ingredient" : "knobi"                            , "allergens" : ["knobi"]},
    {"english": "salad"                        , "category": "gemüse/obst" , "ingredient" : "salat"                            , "allergens" : []},
    {"english": "rucola"                       , "category": "gemüse/obst" , "ingredient" : "rucola"                           , "allergens" : []},
    {"english": "snack veggies"                , "category": "gemüse/obst" , "ingredient" : "snäckgemüse"                      , "allergens" : []},
    {"english": "fryable veggies"              , "category": "gemüse/obst" , "ingredient" : "bratgemüse"                       , "allergens" : []},
    {"english": "fruit"                        , "category": "gemüse/obst" , "ingredient" : "obst"                             , "allergens" : []},
    {"english": "apples"                       , "category": "gemüse/obst" , "ingredient" : "äpfel"                            , "allergens" : []},
    {"english": "pears"                        , "category": "gemüse/obst" , "ingredient" : "birnen"                           , "allergens" : []},
    {"english": "lime"                         , "category": "gemüse/obst" , "ingredient" : "limetten"                         , "allergens" : []},
    {"english": "lemon"                        , "category": "gemüse/obst" , "ingredient" : "zitronen"                         , "allergens" : []},
    {"english": "organic orange"               , "category": "gemüse/obst" , "ingredient" : "bio-orangen"                      , "allergens" : []},
    {"english": "sweet potatos"                , "category": "gemüse/obst" , "ingredient" : "süßkartoffeln"                    , "allergens" : []},
    {"english": "potatos"                      , "category": "gemüse/obst" , "ingredient" : "kartoffeln"                       , "allergens" : []},
    {"english": "brokkoli"                     , "category": "gemüse/obst" , "ingredient" : "brokkoli"                         , "allergens" : []},
    {"english": "green beans"                  , "category": "gemüse/obst" , "ingredient" : "grüne bohnen"                     , "allergens" : []},
    {"english": "ginger"                       , "category": "gemüse/obst" , "ingredient" : "ingwer"                           , "allergens" : []},
    {"english": "pumpkin"                      , "category": "gemüse/obst" , "ingredient" : "kürbis"                           , "allergens" : []},
    {"english": "bell pepper"                  , "category": "gemüse/obst" , "ingredient" : "paprika"                          , "allergens" : []},
    {"english": "celery"                       , "category": "gemüse/obst" , "ingredient" : "sellerie"                         , "allergens" : []},
    {"english": "butternut pumpkin"            , "category": "gemüse/obst" , "ingredient" : "butternutkürbis"                  , "allergens" : []},
    {"english": "leek"                         , "category": "gemüse/obst" , "ingredient" : "lauch"                            , "allergens" : ["lauch"]},
    {"english": "beetroot (fresh)"             , "category": "gemüse/obst" , "ingredient" : "rote beete (roh)"                 , "allergens" : []},
    {"english": "canned tomatos (chopped)"     , "category": "dosen"       , "ingredient" : "dosentomaten (gehackt)"           , "allergens" : []},
    {"english": "canned tomatos (whole)"       , "category": "dosen"       , "ingredient" : "dosentomaten (ganz)"              , "allergens" : []},
    {"english": "canned tomatos (paste)"       , "category": "dosen"       , "ingredient" : "dosentomaten (passiert)"          , "allergens" : []},
    {"english": "tomato concentrate"           , "category": "dosen"       , "ingredient" : "tomatenmark"                      , "allergens" : []},
    {"english": "pickled cucumber"             , "category": "dosen"       , "ingredient" : "saure gurken"                     , "allergens" : []},
    {"english": "canned sweet corn"            , "category": "dosen"       , "ingredient" : "dosenmais"                        , "allergens" : []},
    {"english": "canned green peas"            , "category": "dosen"       , "ingredient" : "dosenerbsen"                      , "allergens" : ["hülsenfrüchte"]},
    {"english": "canned black beans"           , "category": "dosen"       , "ingredient" : "schwarze bohnen (dose)"           , "allergens" : ["hülsenfrüchte"]},
    {"english": "beetroot (pre-cooked)"        , "category": "dosen"       , "ingredient" : "rote beete (gekocht)"             , "allergens" : []},
    {"english": "baked beans"                  , "category": "dosen"       , "ingredient" : "baked beans"                      , "allergens" : ["hülsenfrüchte"]},
    {"english": "sauerkraut"                   , "category": "dosen"       , "ingredient" : "sauerkraut"                       , "allergens" : []},
    {"english": "applesauce"                   , "category": "dosen"       , "ingredient" : "apfelmus"                         , "allergens" : []},
    {"english": "cane sugar"                   , "category": "backen"      , "ingredient" : "rohrzucker"                       , "allergens" : []},
    {"english": "flour"                        , "category": "backen"      , "ingredient" : "mehl"                             , "allergens" : ["gluten"]},
    {"english": "cornstarch"                   , "category": "backen"      , "ingredient" : "stärke"                           , "allergens" : []},
    {"english": "natron"                       , "category": "backen"      , "ingredient" : "natron"                           , "allergens" : []},
    {"english": "dry yeast"                    , "category": "backen"      , "ingredient" : "trockenhefe"                      , "allergens" : []},
    {"english": "sugar"                        , "category": "backen"      , "ingredient" : "zucker"                           , "allergens" : []},
    {"english": "cocoa powder"                 , "category": "backen"      , "ingredient" : "kakao"                            , "allergens" : []},
    {"english": "chocolate"                    , "category": "backen"      , "ingredient" : "kuvertüre/schoki vegan"           , "allergens" : []},
    {"english": "vanilla sugar"                , "category": "backen"      , "ingredient" : "vanillezucker"                    , "allergens" : []},
    {"english": "sugar unicorns"               , "category": "backen"      , "ingredient" : "zuckereinhörner"                  , "allergens" : []},
    {"english": "powdered sugar"               , "category": "backen"      , "ingredient" : "puderzucker"                      , "allergens" : []},
    {"english": "ground hazelnuts"             , "category": "backen"      , "ingredient" : "gemahlene haselnüsse"             , "allergens" : ["haselnüsse"]},
    {"english": "baking powder"                , "category": "backen"      , "ingredient" : "backpulver"                       , "allergens" : []},
    {"english": "olive oil"                    , "category": "öl/essig"    , "ingredient" : "olivenöl"                         , "allergens" : []},
    {"english": "linseed oil"                  , "category": "öl/essig"    , "ingredient" : "leinöl"                           , "allergens" : []},
    {"english": "oil"                          , "category": "öl/essig"    , "ingredient" : "öl"                               , "allergens" : []},
    {"english": "balsamico"                    , "category": "öl/essig"    , "ingredient" : "balsamico"                        , "allergens" : ["histamin"]},
    {"english": "balsamico (white)"            , "category": "öl/essig"    , "ingredient" : "balsamico (hell)"                 , "allergens" : []},
    {"english": "apple cider vinegar"          , "category": "öl/essig"    , "ingredient" : "apfelessig"                       , "allergens" : []},
    {"english": "white wine vinegar"           , "category": "öl/essig"    , "ingredient" : "weißweinessig"                    , "allergens" : []},
    {"english": "laurel leaves"                , "category": "gewürze"     , "ingredient" : "lorbeer"                          , "allergens" : []},
    {"english": "pepper"                       , "category": "gewürze"     , "ingredient" : "pfeffer"                          , "allergens" : []},
    {"english": "pepper whole"                 , "category": "gewürze"     , "ingredient" : "pfeffer ganz"                     , "allergens" : []},
    {"english": "salt"                         , "category": "gewürze"     , "ingredient" : "salz"                             , "allergens" : []},
    {"english": "mustard"                      , "category": "gewürze"     , "ingredient" : "senf"                             , "allergens" : []},
    {"english": "nutmeg"                       , "category": "gewürze"     , "ingredient" : "muskat"                           , "allergens" : []},
    {"english": "smoked paprika"               , "category": "gewürze"     , "ingredient" : "geräuchertes paprikapulver"       , "allergens" : []},
    {"english": "cumin"                        , "category": "gewürze"     , "ingredient" : "kreuzkümmel"                      , "allergens" : []},
    {"english": "thyme"                        , "category": "gewürze"     , "ingredient" : "thymian"                          , "allergens" : []},
    {"english": "caraway"                      , "category": "gewürze"     , "ingredient" : "kümmel"                           , "allergens" : []},
    {"english": "vanilla"                      , "category": "gewürze"     , "ingredient" : "vanille"                          , "allergens" : []},
    {"english": "black onion seeds"            , "category": "gewürze"     , "ingredient" : "schwarzkümmel"                    , "allergens" : []},
    {"english": "turmeric"                     , "category": "gewürze"     , "ingredient" : "kurkuma"                          , "allergens" : []},
    {"english": "cinnamon"                     , "category": "gewürze"     , "ingredient" : "zimt"                             , "allergens" : []},
    {"english": "oregano"                      , "category": "gewürze"     , "ingredient" : "oregano"                          , "allergens" : []},
    {"english": "rosemary"                     , "category": "gewürze"     , "ingredient" : "rosmarin"                         , "allergens" : []},
    {"english": "allspice"                     , "category": "gewürze"     , "ingredient" : "allspice"                         , "allergens" : []},
    {"english": "curry powder"                 , "category": "gewürze"     , "ingredient" : "curry (pulver)"                   , "allergens" : []},
    {"english": "paprika powder"               , "category": "gewürze"     , "ingredient" : "paprika (pulver)"                 , "allergens" : []},
    {"english": "chili powder"                 , "category": "gewürze"     , "ingredient" : "chili (pulver)"                   , "allergens" : []},
    {"english": "ginger powder"                , "category": "gewürze"     , "ingredient" : "ingwer (pulver)"                  , "allergens" : []},
    {"english": "vegetable broth"              , "category": "gewürze"     , "ingredient" : "gemüsebrühe"                      , "allergens" : []},
    {"english": "sojahack (dry)"               , "category": "trockenware" , "ingredient" : "sojahack (trocken)"               , "allergens" : ["soja"]},
    {"english": "lasagna sheets"               , "category": "trockenware" , "ingredient" : "lasagneplatten"                   , "allergens" : ["gluten"]},
    {"english": "pasta"                        , "category": "trockenware" , "ingredient" : "pasta"                            , "allergens" : ["gluten"]},
    {"english": "couscous"                     , "category": "trockenware" , "ingredient" : "couscous"                         , "allergens" : ["gluten"]},
    {"english": "grünkern"                     , "category": "trockenware" , "ingredient" : "grünkern"                         , "allergens" : ["gluten"]},
    {"english": "basmati"                      , "category": "trockenware" , "ingredient" : "basmati"                          , "allergens" : []},
    {"english": "short grain rice"             , "category": "trockenware" , "ingredient" : "milchreis"                        , "allergens" : []},
    {"english": "brown lentils"                , "category": "trockenware" , "ingredient" : "braune linsen (tellerlinsen)"     , "allergens" : ["hülsenfrüchte"]},
    {"english": "red lentils"                  , "category": "trockenware" , "ingredient" : "rote linsen"                      , "allergens" : ["hülsenfrüchte"]},
    {"english": "sunflower seeds"              , "category": "trockenware" , "ingredient" : "sonnenblumenkerne"                , "allergens" : []},
    {"english": "kidney beans (dry, wet x 4)"  , "category": "trockenware" , "ingredient" : "kidneybohnen (trocken, nass x 4)" , "allergens" : ["hülsenfrüchte"]},
    {"english": "white beans (dry, wet x 4)"   , "category": "trockenware" , "ingredient" : "weiße bohnen (trocken, nass x 4)" , "allergens" : ["hülsenfrüchte"]},
    {"english": "chickpeas (dry, wet x 2)"     , "category": "trockenware" , "ingredient" : "kichererbsen (trocken, nass x 2)" , "allergens" : ["hülsenfrüchte"]},
    {"english": "capers"                       , "category": "trockenware" , "ingredient" : "kapern"                           , "allergens" : []},
    {"english": "dried tomatos in oil"         , "category": "trockenware" , "ingredient" : "getrocknete tomaten in öl"        , "allergens" : []},
    {"english": "oats"                         , "category": "frühstück"   , "ingredient" : "haferflocken"                     , "allergens" : ["gluten"]},
    {"english": "vegan sugar cereals"          , "category": "frühstück"   , "ingredient" : "veganes zuckermüsli"              , "allergens" : ["gluten"]},
    {"english": "coffee"                       , "category": "frühstück"   , "ingredient" : "kaffe"                            , "allergens" : []},
    {"english": "black tea"                    , "category": "frühstück"   , "ingredient" : "schwarztee"                       , "allergens" : []},
    {"english": "herbal tea"                   , "category": "frühstück"   , "ingredient" : "kräutertee"                       , "allergens" : []},
    {"english": "jam"                          , "category": "frühstück"   , "ingredient" : "marmelade"                        , "allergens" : []},
    {"english": "rose jam"                     , "category": "frühstück"   , "ingredient" : "rosenmarmelade"                   , "allergens" : []},
    {"english": "bread"                        , "category": "frühstück"   , "ingredient" : "brot"                             , "allergens" : ["gluten"]},
    {"english": "smoked tofu"                  , "category": "kühlware"    , "ingredient" : "räuchertofu"                      , "allergens" : ["soja"]},
    {"english": "sausages"                     , "category": "kühlware"    , "ingredient" : "würstchen"                        , "allergens" : []},
    {"english": "potato dumpling dough"        , "category": "kühlware"    , "ingredient" : "kloßteig"                         , "allergens" : []},
    {"english": "tk-rösti"                     , "category": "kühlware"    , "ingredient" : "tk-rösti"                         , "allergens" : []},
    {"english": "tk-peas"                      , "category": "kühlware"    , "ingredient" : "tk-erbsen"                        , "allergens" : ["hülsenfrüchte"]},
    {"english": "margerine"                    , "category": "kühlware"    , "ingredient" : "margerine"                        , "allergens" : []},
    {"english": "margerine (small packs)"      , "category": "kühlware"    , "ingredient" : "margerine (kleine packungen)"     , "allergens" : []},
    {"english": "soy milk"                     , "category": "kühlware"    , "ingredient" : "sojamilch"                        , "allergens" : ["soja"]},
    {"english": "soy cream"                    , "category": "kühlware"    , "ingredient" : "sojasahne"                        , "allergens" : ["soja"]},
    {"english": "soy yoghurt"                  , "category": "kühlware"    , "ingredient" : "sojajoghurt"                      , "allergens" : ["soja"]},
    {"english": "oat milk"                     , "category": "kühlware"    , "ingredient" : "hafermilch"                       , "allergens" : ["gluten"]},
    {"english": "genuss-block"                 , "category": "kühlware"    , "ingredient" : "genuss-block"                     , "allergens" : []},
    {"english": "fresh yeast"                  , "category": "kühlware"    , "ingredient" : "frische hefe"                     , "allergens" : []},
    {"english": "crewcare"                     , "category": "snacks"      , "ingredient" : "crewcare"                         , "allergens" : []},
    {"english": "puffed rice cakes"            , "category": "snacks"      , "ingredient" : "reiswaffeln"                      , "allergens" : []},
    {"english": "crisps"                       , "category": "snacks"      , "ingredient" : "chips"                            , "allergens" : []},
    {"english": "pecans"                       , "category": "snacks"      , "ingredient" : "pekannüsse"                       , "allergens" : []},
    {"english": "walnuts"                      , "category": "snacks"      , "ingredient" : "walnüsse"                         , "allergens" : ["walnüsse"]},
    {"english": "peanuts"                      , "category": "snacks"      , "ingredient" : "erdnüsse"                         , "allergens" : ["erdnüsse"]},
    {"english": "cashew nuts"                  , "category": "snacks"    , "ingredient" : "cashewnüsse"                        , "allergens" : []},
    ]

metrodb = TinyDB(storage=MemoryStorage)
metrodb.insert_multiple(entries)

def cat_sort(cat: str):
    categories = {
      "hygiene"    : 1,
      "getränke"   : 2,
      "gemüse/obst"  : 3,
      "baking"     : 4,
      "gewürze/öl" : 5,
      "oils"       : 6,
      "cans"       : 7,
      "trockenware": 8,
      "milk"       : 9,
      "frühstück"  : 10,
      "snacks"     : 11,
      "nometro"    : 100,
    }
    if cat in categories:
        return categories[cat]
    else:
        return 0
